FROM python:3.7

WORKDIR /pyresparser
COPY . .

RUN pip install -U pip setuptools virtualenv --force-reinstall  \
 && pip install --no-cache-dir -r requirements.txt \
 && python setup.py install \
 && python -m spacy download en_core_web_sm \
 && python -m nltk.downloader stopwords \
 && python -m nltk.downloader words

EXPOSE 10001

CMD ["python", "parser.py"]