FROM python:3.7

WORKDIR /pyresparser
COPY . .

RUN pip install -U pip setuptools virtualenv --force-reinstall  \
 && pip install --no-cache-dir -r requirements.txt \
 && python setup.py install \
 && python -m spacy dlownload en_core_web_sm \
 && python -m nltk.downloader stopwords

EXPOSE 8501

CMD ["streamlit", "run", "cv_parser.py", "--browser.serverAddress=0.0.0.0", "--server.maxUploadSize=100"]